# nginx.conf
server {
  listen 80; # Escucha en el puerto 80

  # Define la raíz de los archivos estáticos de tu aplicación Angular
  root /usr/share/nginx/html;

  # Habilita la compresión Gzip para mejorar el rendimiento
  gzip on;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
  gzip_proxied any;
  gzip_vary on;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;

location = /index.html {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Pragma "no-cache";
    add_header Expires "0";
    try_files $uri =404;
  }

  # Intenta servir el archivo solicitado, si no existe, redirige a index.html
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Configuración para archivos de caché
  location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
    expires 1y;
    log_not_found off;
    add_header Cache-Control "public";
  }
}
