# Identificación del proyecto en SonarQube
sonar.projectKey=angular-tets
sonar.projectName=Angular Tests
sonar.sourceEncoding=UTF-8

# Código fuente
sonar.sources=src

# Excluir carpetas que no aportan valor
sonar.exclusions=**/node_modules/**,src/environments/**

# Tests
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Cobertura (Karma / Jasmine)
sonar.typescript.lcov.reportPaths=coverage/**/lcov.info

# Conexión SonarQube
sonar.host.url=http://localhost:9000
sonar.token=sqp_42dd3d51fef8477e5e6d014144c0b981ed70e338
